//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Index.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Index::genText(const DrTemplateData& Index_view_data)
{
	drogon::OStringStream Index_tmp_stream;
	std::string layoutName{""};
	Index_tmp_stream << "<!DOCTYPE html>\n";
	Index_tmp_stream << "<html lang=\"ru\">\n";
	Index_tmp_stream << "<head>\n";
	Index_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	Index_tmp_stream << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	Index_tmp_stream << "    <title>Выбор направления</title>\n";
	Index_tmp_stream << "    <link rel=\"stylesheet\" href=\"styles/index_style.css\"> \n";
	Index_tmp_stream << "    <link rel=\"stylesheet\" href=\"styles/style.css\">\n";
	Index_tmp_stream << "    <script defer src=\"scripts/index.js\"></script>\n";
	Index_tmp_stream << "</head>\n";
	Index_tmp_stream << "<body>\n";
	Index_tmp_stream << "    <header class=\"index_header\">\n";
	Index_tmp_stream << "        <a class=\"index_header_a\" href=\"index.html\">\n";
	Index_tmp_stream << "            <img class=\"index_header_logo\" src=\"img/logo.svg\">\n";
	Index_tmp_stream << "        </a>\n";
	Index_tmp_stream << "        <h1>ПеревозОчка</h1>\n";
	Index_tmp_stream << "        <button class=\"index_header_profile_btn\"><a class=\"index_header_profile_btn_a\" href=\"profile.html\">Профиль</a></button>\n";
	Index_tmp_stream << "    </header>\n";
	Index_tmp_stream << "    <div class=\"container\">\n";
	Index_tmp_stream << "        <h2>Выберите направление:</h2>\n";
Index_tmp_stream<<"\n";
	Index_tmp_stream << "        <form action=\"#\" method=\"post\" id=\"registrationForm\"> \n";
	Index_tmp_stream << "            <div class=\"destination_div\">\n";
	Index_tmp_stream << "                <div class=\"input-container\">\n";
	Index_tmp_stream << "                    <input type=\"text\" id=\"departure\" name=\"departure\" placeholder=\"Город отправления\" oninput=\"checkForm()\">\n";
	Index_tmp_stream << "                </div>\n";
	Index_tmp_stream << "                <div class=\"input-container\">\n";
	Index_tmp_stream << "                    <input type=\"text\" id=\"arrival\" name=\"arrival\" placeholder=\"Город прибытия\" oninput=\"checkForm()\">\n";
	Index_tmp_stream << "                </div>\n";
	Index_tmp_stream << "            </div>\n";
Index_tmp_stream<<"\n";
	Index_tmp_stream << "            <h2>Выберите машину:</h2>\n";
	Index_tmp_stream << "                <div class=\"cars_div\">\n";
	Index_tmp_stream << "                    <input class=\"car_input\" id=\"gaz_bort_input\" name=\"car\" type=\"radio\" value=\"gaz_bort_4m\" onchange=\"checkForm()\">\n";
	Index_tmp_stream << "                    <input class=\"car_input\" id=\"gaz_tent_input\" name=\"car\" type=\"radio\" value=\"gaz_tent_4m\" onchange=\"checkForm()\">\n";
	Index_tmp_stream << "                    <input class=\"car_input\" id=\"gaz_pir_input\" name=\"car\" type=\"radio\" value=\"gaz_pir_4m\" onchange=\"checkForm()\">\n";
	Index_tmp_stream << "                    <input class=\"car_input\" id=\"fur_bort_input\" name=\"car\" type=\"radio\" value=\"fur_bort_6m\" onchange=\"checkForm()\">\n";
Index_tmp_stream<<"\n";
	Index_tmp_stream << "                    <label for=\"gaz_bort_input\" class=\"car_label car_label_one\">\n";
	Index_tmp_stream << "                        <h3>Газель бортовая 4м</h3>\n";
	Index_tmp_stream << "                        <img class=\"car_img\" src=\"img/gaz_bort_4m.png\" alt=\"\">\n";
	Index_tmp_stream << "                        <div class=\"car_descr_div\">\n";
	Index_tmp_stream << "                            <span class=\"weight\"><img class=\"weight_img\" src=\"img/weight.svg\"><p class=\"car_right_text_div_p\">1.5 т</p></span>\n";
	Index_tmp_stream << "                            <span class=\"lenght\"><img class=\"lenght_img\" src=\"img/length.svg\"><p class=\"car_right_div_p\">4 м</p></span>   \n";
	Index_tmp_stream << "                            <span class=\"width\"><img class=\"width_img\" src=\"img/width.svg\"><p class=\"car_right_div_p\">1.7 м</p></span>   \n";
	Index_tmp_stream << "                        </div>\n";
	Index_tmp_stream << "                    </label>\n";
	Index_tmp_stream << " \n";
	Index_tmp_stream << "                    <label for=\"gaz_tent_input\" class=\"car_label car_label_two\">\n";
	Index_tmp_stream << "                        <h3>Газель тентованная 4м</h3>\n";
	Index_tmp_stream << "                        <img class=\"car_img\" src=\"img/gaz_tent_4m.png\" alt=\"\">\n";
	Index_tmp_stream << "                        <div class=\"car_descr_div\">\n";
	Index_tmp_stream << "                            <span class=\"weight\"><img class=\"weight_img\" src=\"img/weight.svg\"><p class=\"car_right_text_div_p\">1.5 т</p></span>\n";
	Index_tmp_stream << "                            <span class=\"lenght\"><img class=\"lenght_img\" src=\"img/length.svg\"><p class=\"car_right_div_p\">4 м</p></span>   \n";
	Index_tmp_stream << "                            <span class=\"width\"><img class=\"width_img\" src=\"img/width.svg\"><p class=\"car_right_div_p\">1.7 м</p></span>   \n";
	Index_tmp_stream << "                        </div>\n";
	Index_tmp_stream << "                    </label>     \n";
Index_tmp_stream<<"\n";
	Index_tmp_stream << "                    <label for=\"gaz_pir_input\" class=\"car_label car_label_three\">                       \n";
	Index_tmp_stream << "                        <h3>Газель пирамида 4м</h3>\n";
	Index_tmp_stream << "                        <img class=\"car_img\" src=\"img/gaz_pir_4m.png\" alt=\"\">\n";
	Index_tmp_stream << "                        <div class=\"car_descr_div\">\n";
	Index_tmp_stream << "                            <span class=\"weight\"><img class=\"weight_img\" src=\"img/weight.svg\"><p class=\"car_right_text_div_p\">1.5 т</p></span>\n";
	Index_tmp_stream << "                            <span class=\"lenght\"><img class=\"lenght_img\" src=\"img/length.svg\"><p class=\"car_right_div_p\">4 м</p></span>   \n";
	Index_tmp_stream << "                            <span class=\"width\"><img class=\"width_img\" src=\"img/width.svg\"><p class=\"car_right_div_p\">1.7 м</p></span>   \n";
	Index_tmp_stream << "                        </div>\n";
	Index_tmp_stream << "                    </label>\n";
Index_tmp_stream<<"\n";
	Index_tmp_stream << "                    <label for=\"fur_bort_input\" class=\"car_label car_label_four\">       \n";
	Index_tmp_stream << "                        <h3>Грузовик фургон 6м</h3>\n";
	Index_tmp_stream << "                        <img class=\"car_img\" src=\"img/fur_bort_6m.png\" alt=\"\">\n";
	Index_tmp_stream << "                        <div class=\"car_descr_div\">\n";
	Index_tmp_stream << "                            <span class=\"weight\"><img class=\"weight_img\" src=\"img/weight.svg\"><p class=\"car_right_text_div_p\">10 т</p></span>\n";
	Index_tmp_stream << "                            <span class=\"lenght\"><img class=\"lenght_img\" src=\"img/length.svg\"><p class=\"car_right_div_p\">6 м</p></span>   \n";
	Index_tmp_stream << "                            <span class=\"width\"><img class=\"width_img\" src=\"img/width.svg\"><p class=\"car_right_div_p\">2.4 м</p></span>   \n";
	Index_tmp_stream << "                        </div>\n";
	Index_tmp_stream << "                    </label>\n";
	Index_tmp_stream << "                </div>\n";
	Index_tmp_stream << "            <div class=\"insurance_div\">\n";
	Index_tmp_stream << "                <input class=\"insurance_input\" id=\"insurance_input\" name=\"ensurance\" type=\"checkbox\" value=\"is_insurance\">\n";
	Index_tmp_stream << "                <label for=\"insurance_input\" class=\"insurance_input_label\">Страховка</label>\n";
	Index_tmp_stream << "            </div>\n";
	Index_tmp_stream << "            \n";
	Index_tmp_stream << "            <div class=\"btns_div\">\n";
	Index_tmp_stream << "                <button class=\"count_cost_btn\" type=\"submit\" id=\"countCostBtn\" disabled>Расчитать стоимость</button>\n";
	Index_tmp_stream << "                <button class=\"reset_btn\" type=\"reset\" id=\"resetBtn\">Сбросить</button>\n";
	Index_tmp_stream << "            </div>\n";
Index_tmp_stream<<"\n";
	Index_tmp_stream << "        </form>\n";
	Index_tmp_stream << "    </div>\n";
Index_tmp_stream<<"\n";
	Index_tmp_stream << "    <div class=\"costs_container\">\n";
Index_tmp_stream<<"\n";
	Index_tmp_stream << "    </div>\n";
	Index_tmp_stream << "</body>\n";
	Index_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(Index_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Index_view_data;
auto str = std::move(Index_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
