//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Profile:public drogon::DrTemplate<Profile>
{
public:
	Profile(){};
	virtual ~Profile(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
