//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class Register:public drogon::DrTemplate<Register>
{
public:
	Register(){};
	virtual ~Register(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
