//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "Register.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string Register::genText(const DrTemplateData& Register_view_data)
{
	drogon::OStringStream Register_tmp_stream;
	std::string layoutName{""};
	Register_tmp_stream << "<!DOCTYPE html>\n";
	Register_tmp_stream << "<html lang=\"ru\">\n";
	Register_tmp_stream << "<head>\n";
	Register_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	Register_tmp_stream << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	Register_tmp_stream << "    <title>Регистрация</title>\n";
	Register_tmp_stream << "    <link rel=\"stylesheet\" href=\"styles/auth_style.css\"> \n";
	Register_tmp_stream << "    <link rel=\"stylesheet\" href=\"styles/style.css\">\n";
	Register_tmp_stream << "    <script defer src=\"scripts/register.js\"></script>\n";
	Register_tmp_stream << "</head>\n";
	Register_tmp_stream << "<body>\n";
	Register_tmp_stream << "    <div class=\"container\">\n";
	Register_tmp_stream << "        <h1>Регистрация</h1>\n";
	Register_tmp_stream << "        <form action=\"/register\" method=\"post\" id=\"registrationForm\">\n";
	Register_tmp_stream << "            <label for=\"firstName\">Имя:</label>\n";
	Register_tmp_stream << "            <input type=\"text\" id=\"firstName\" name=\"firstName\" required>\n";
Register_tmp_stream<<"\n";
	Register_tmp_stream << "            <label for=\"lastName\">Фамилия:</label>\n";
	Register_tmp_stream << "            <input type=\"text\" id=\"lastName\" name=\"lastName\" required>\n";
Register_tmp_stream<<"\n";
	Register_tmp_stream << "            <label for=\"email\">Email:</label>\n";
	Register_tmp_stream << "            <input type=\"email\" id=\"email\" name=\"email\" required>\n";
Register_tmp_stream<<"\n";
	Register_tmp_stream << "            <label for=\"password\">Пароль, не меньше 7 символов:</label>\n";
	Register_tmp_stream << "            <input type=\"password\" id=\"password\" name=\"password\" required>\n";
Register_tmp_stream<<"\n";
	Register_tmp_stream << "            <label for=\"confirmPassword\">Подтвердите пароль:</label>\n";
	Register_tmp_stream << "            <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" required>\n";
Register_tmp_stream<<"\n";
	Register_tmp_stream << "            <button type=\"submit\" name=\"submitButton\">Создать аккаунт</button>\n";
	Register_tmp_stream << "        </form>\n";
	Register_tmp_stream << "        <p>\n";
	Register_tmp_stream << "            Уже есть аккаунт? <a href=\"login.html\">Войти</a>\n";
	Register_tmp_stream << "        </p>\n";
	Register_tmp_stream << "    </div>\n";
	Register_tmp_stream << "</body>\n";
	Register_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(Register_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = Register_view_data;
auto str = std::move(Register_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
